INFO 2024-08-22 15:45:32,442 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 15:45:32,442 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 15:45:48,147 basehttp "POST /api/contracts/ HTTP/1.1" 201 3
INFO 2024-08-22 15:45:48,147 basehttp "POST /api/contracts/ HTTP/1.1" 201 3
INFO 2024-08-22 15:45:53,182 basehttp "POST /api/contracts/105/parties/ HTTP/1.1" 201 4
INFO 2024-08-22 15:45:53,182 basehttp "POST /api/contracts/105/parties/ HTTP/1.1" 201 4
INFO 2024-08-22 15:45:55,546 basehttp "POST /api/contracts/105/settlements/ HTTP/1.1" 201 4
INFO 2024-08-22 15:45:55,546 basehttp "POST /api/contracts/105/settlements/ HTTP/1.1" 201 4
INFO 2024-08-22 15:45:59,047 basehttp "POST /api/contracts/105/transactions/ HTTP/1.1" 201 4
INFO 2024-08-22 15:45:59,047 basehttp "POST /api/contracts/105/transactions/ HTTP/1.1" 201 4
INFO 2024-08-22 15:45:59,458 basehttp "GET /api/contracts/105/settlements/ HTTP/1.1" 200 706
INFO 2024-08-22 15:45:59,458 basehttp "GET /api/contracts/105/settlements/ HTTP/1.1" 200 706
INFO 2024-08-22 15:45:59,968 basehttp "GET /api/contracts/105/settlements/ HTTP/1.1" 200 706
INFO 2024-08-22 15:45:59,968 basehttp "GET /api/contracts/105/settlements/ HTTP/1.1" 200 706
INFO 2024-08-22 15:46:14,609 basehttp "GET /api/contract-events/?contract_idx=105 HTTP/1.1" 200 1363
INFO 2024-08-22 15:46:14,609 basehttp "GET /api/contract-events/?contract_idx=105 HTTP/1.1" 200 1363
INFO 2024-08-22 16:41:02,799 basehttp "GET /api/contracts/105/settlements/ HTTP/1.1" 200 706
INFO 2024-08-22 16:41:02,799 basehttp "GET /api/contracts/105/settlements/ HTTP/1.1" 200 706
INFO 2024-08-22 16:41:31,654 basehttp "GET /api/accounts/ HTTP/1.1" 200 2
INFO 2024-08-22 16:41:31,654 basehttp "GET /api/accounts/ HTTP/1.1" 200 2
INFO 2024-08-22 17:21:52,066 basehttp "GET /api/accounts/ HTTP/1.1" 200 2
INFO 2024-08-22 17:21:52,066 basehttp "GET /api/accounts/ HTTP/1.1" 200 2
INFO 2024-08-22 17:22:19,517 basehttp "GET /api/accounts/ HTTP/1.1" 200 1009
INFO 2024-08-22 17:22:19,517 basehttp "GET /api/accounts/ HTTP/1.1" 200 1009
INFO 2024-08-22 17:26:53,263 basehttp "GET /api/accounts/ HTTP/1.1" 200 2
INFO 2024-08-22 17:26:53,263 basehttp "GET /api/accounts/ HTTP/1.1" 200 2
INFO 2024-08-22 17:26:55,005 basehttp "GET /api/accounts/ HTTP/1.1" 200 2
INFO 2024-08-22 17:26:55,005 basehttp "GET /api/accounts/ HTTP/1.1" 200 2
INFO 2024-08-22 17:27:38,807 basehttp "GET /api/accounts/ HTTP/1.1" 200 2
INFO 2024-08-22 17:27:38,807 basehttp "GET /api/accounts/ HTTP/1.1" 200 2
INFO 2024-08-22 17:27:59,896 basehttp "GET /api/accounts/ HTTP/1.1" 200 1009
INFO 2024-08-22 17:27:59,896 basehttp "GET /api/accounts/ HTTP/1.1" 200 1009
INFO 2024-08-22 17:32:55,324 basehttp "GET /api/accounts/ HTTP/1.1" 200 1009
INFO 2024-08-22 17:32:55,324 basehttp "GET /api/accounts/ HTTP/1.1" 200 1009
INFO 2024-08-22 17:45:57,110 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 17:45:57,110 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
WARNING 2024-08-22 17:46:17,029 basehttp "GET /api/accounts/?bank=invalid HTTP/1.1" 404 81
WARNING 2024-08-22 17:46:17,029 basehttp "GET /api/accounts/?bank=invalid HTTP/1.1" 404 81
INFO 2024-08-22 17:46:25,212 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 17:46:25,212 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 17:47:41,365 basehttp "GET /api/recipients/?bank=mercury HTTP/1.1" 200 7799
INFO 2024-08-22 17:47:41,365 basehttp "GET /api/recipients/?bank=mercury HTTP/1.1" 200 7799
INFO 2024-08-22 17:50:06,708 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 17:50:06,708 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 18:59:48,873 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 18:59:48,873 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 19:37:00,540 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 19:37:00,540 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 19:37:00,825 basehttp "GET /api/recipients/?bank=mercury HTTP/1.1" 200 7799
INFO 2024-08-22 19:37:00,825 basehttp "GET /api/recipients/?bank=mercury HTTP/1.1" 200 7799
INFO 2024-08-22 19:37:44,509 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 19:37:44,509 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 19:37:44,796 basehttp "GET /api/recipients/?bank=mercury HTTP/1.1" 200 7799
INFO 2024-08-22 19:37:44,796 basehttp "GET /api/recipients/?bank=mercury HTTP/1.1" 200 7799
INFO 2024-08-22 19:38:06,921 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 19:38:06,921 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 19:38:07,208 basehttp "GET /api/recipients/?bank=mercury HTTP/1.1" 200 7799
INFO 2024-08-22 19:38:07,208 basehttp "GET /api/recipients/?bank=mercury HTTP/1.1" 200 7799
INFO 2024-08-22 19:46:06,462 basehttp "POST /api/contracts/ HTTP/1.1" 201 3
INFO 2024-08-22 19:46:06,462 basehttp "POST /api/contracts/ HTTP/1.1" 201 3
INFO 2024-08-22 19:46:12,119 basehttp "POST /api/contracts/106/parties/ HTTP/1.1" 201 4
INFO 2024-08-22 19:46:12,119 basehttp "POST /api/contracts/106/parties/ HTTP/1.1" 201 4
WARNING 2024-08-22 19:46:12,132 basehttp "POST /api/contracts/106/settlements/ HTTP/1.1" 400 47
WARNING 2024-08-22 19:46:12,132 basehttp "POST /api/contracts/106/settlements/ HTTP/1.1" 400 47
INFO 2024-08-22 19:47:02,626 basehttp "POST /api/contracts/ HTTP/1.1" 201 3
INFO 2024-08-22 19:47:02,626 basehttp "POST /api/contracts/ HTTP/1.1" 201 3
INFO 2024-08-22 19:47:08,544 basehttp "POST /api/contracts/107/parties/ HTTP/1.1" 201 4
INFO 2024-08-22 19:47:08,544 basehttp "POST /api/contracts/107/parties/ HTTP/1.1" 201 4
INFO 2024-08-22 19:47:10,310 basehttp "POST /api/contracts/107/settlements/ HTTP/1.1" 201 4
INFO 2024-08-22 19:47:10,310 basehttp "POST /api/contracts/107/settlements/ HTTP/1.1" 201 4
INFO 2024-08-22 19:47:14,159 basehttp "POST /api/contracts/107/transactions/ HTTP/1.1" 201 4
INFO 2024-08-22 19:47:14,159 basehttp "POST /api/contracts/107/transactions/ HTTP/1.1" 201 4
INFO 2024-08-22 19:47:14,656 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 19:47:14,656 basehttp "GET /api/accounts/?bank=mercury HTTP/1.1" 200 1009
INFO 2024-08-22 19:47:15,047 basehttp "GET /api/recipients/?bank=mercury HTTP/1.1" 200 7799
INFO 2024-08-22 19:47:15,047 basehttp "GET /api/recipients/?bank=mercury HTTP/1.1" 200 7799
INFO 2024-08-22 19:48:14,033 basehttp "GET /api/contracts/ HTTP/1.1" 200 60025
INFO 2024-08-22 19:48:14,033 basehttp "GET /api/contracts/ HTTP/1.1" 200 60025
INFO 2024-08-22 19:48:45,020 basehttp "GET /api/contracts/107/ HTTP/1.1" 200 509
INFO 2024-08-22 19:48:45,020 basehttp "GET /api/contracts/107/ HTTP/1.1" 200 509
INFO 2024-08-22 19:49:05,313 basehttp "GET /api/contracts/107/transactions/ HTTP/1.1" 200 773
INFO 2024-08-22 19:49:05,313 basehttp "GET /api/contracts/107/transactions/ HTTP/1.1" 200 773
INFO 2024-08-22 19:58:20,324 basehttp "POST /api/accounts/61396d72-e780-11ee-b69b-137ed758771c/pay-advance/ HTTP/1.1" 200 4
INFO 2024-08-22 19:58:20,324 basehttp "POST /api/accounts/61396d72-e780-11ee-b69b-137ed758771c/pay-advance/ HTTP/1.1" 200 4
INFO 2024-08-22 20:07:41,275 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/urls.py changed, reloading.
INFO 2024-08-22 20:07:41,275 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/urls.py changed, reloading.
Fetching secret value for devnet/rotating-keys from AWS Secrets Manager
Fetching secret value for devnet/static-keys from AWS Secrets Manager
Performing system checks...

Connection successful
Contract loaded
System check identified no issues (0 silenced).
August 22, 2024 - 15:45:32
Django version 5.0.5, using settings 'project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Error fetching accounts: 401 Client Error: Unauthorized for url: https://api-sandbox.mercury.com/api/v1/accounts
Error fetching accounts: 401 Client Error: Unauthorized for url: https://api-sandbox.mercury.com/api/v1/accounts
Error fetching accounts: 401 Client Error: Unauthorized for url: https://api-sandbox.mercury.com/api/v1/accounts
Error fetching accounts: 401 Client Error: Unauthorized for url: https://api-sandbox.mercury.com/api/v1/accounts
Error fetching accounts: 401 Client Error: Unauthorized for url: https://api-sandbox.mercury.com/api/v1/accounts
INFO 2024-08-22 20:07:42,407 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:07:42,407 autoreload Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/project/urls.py", line 9, in <module>
    path('api/', include('api.urls')), 
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/api/urls.py", line 29
    path('accounts/<str:account_id>/advance/', AccountViewSet.as_view({'get',:'get','post':'pay_advance'}), name='advance'),
                                                                             ^
SyntaxError: invalid syntax
INFO 2024-08-22 20:07:57,741 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/urls.py changed, reloading.
INFO 2024-08-22 20:07:57,741 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/urls.py changed, reloading.
Fetching secret value for devnet/rotating-keys from AWS Secrets Manager
Fetching secret value for devnet/static-keys from AWS Secrets Manager
Performing system checks...

INFO 2024-08-22 20:07:58,574 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:07:58,574 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:09:43,612 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/views/account_views.py changed, reloading.
INFO 2024-08-22 20:09:43,612 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/views/account_views.py changed, reloading.
Fetching secret value for devnet/rotating-keys from AWS Secrets Manager
Fetching secret value for devnet/static-keys from AWS Secrets Manager
Performing system checks...

Connection successful
Contract loaded
System check identified no issues (0 silenced).
August 22, 2024 - 20:07:59
Django version 5.0.5, using settings 'project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

INFO 2024-08-22 20:09:44,842 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:09:44,842 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:09:49,751 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/views/recipient_views.py changed, reloading.
INFO 2024-08-22 20:09:49,751 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/views/recipient_views.py changed, reloading.
Fetching secret value for devnet/rotating-keys from AWS Secrets Manager
Fetching secret value for devnet/static-keys from AWS Secrets Manager
Performing system checks...

Connection successful
Contract loaded
System check identified no issues (0 silenced).
August 22, 2024 - 20:09:45
Django version 5.0.5, using settings 'project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

INFO 2024-08-22 20:09:50,647 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:09:50,647 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:10:00,591 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/views/deposit_views.py changed, reloading.
INFO 2024-08-22 20:10:00,591 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/views/deposit_views.py changed, reloading.
Fetching secret value for devnet/rotating-keys from AWS Secrets Manager
Fetching secret value for devnet/static-keys from AWS Secrets Manager
Performing system checks...

Connection successful
Contract loaded
System check identified no issues (0 silenced).
August 22, 2024 - 20:09:51
Django version 5.0.5, using settings 'project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

INFO 2024-08-22 20:10:01,826 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:10:01,826 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:13:16,722 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/views/__init__.py changed, reloading.
INFO 2024-08-22 20:13:16,722 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/views/__init__.py changed, reloading.
Fetching secret value for devnet/rotating-keys from AWS Secrets Manager
Fetching secret value for devnet/static-keys from AWS Secrets Manager
Performing system checks...

Connection successful
Contract loaded
System check identified no issues (0 silenced).
August 22, 2024 - 20:10:02
Django version 5.0.5, using settings 'project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

INFO 2024-08-22 20:13:17,654 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:13:17,654 autoreload Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/project/urls.py", line 9, in <module>
    path('api/', include('api.urls')), 
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/api/urls.py", line 16, in <module>
    from .views.csrf_token_views import get_csrf_token
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/api/views/__init__.py", line 14, in <module>
    from .residual_views import ResidualViewSet
ImportError: cannot import name 'ResidualViewSet' from 'api.views.residual_views' (/Users/davidnichamoff/Projects/FIZIT_DEV/api/views/residual_views.py)
INFO 2024-08-22 20:13:49,884 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/views/__init__.py changed, reloading.
INFO 2024-08-22 20:13:49,884 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/views/__init__.py changed, reloading.
Fetching secret value for devnet/rotating-keys from AWS Secrets Manager
Fetching secret value for devnet/static-keys from AWS Secrets Manager
Performing system checks...

Connection successful
Contract loaded
INFO 2024-08-22 20:13:50,772 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:13:50,772 autoreload Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/project/urls.py", line 9, in <module>
    path('api/', include('api.urls')), 
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/api/urls.py", line 16, in <module>
    from .views.csrf_token_views import get_csrf_token
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/api/views/__init__.py", line 14, in <module>
    from .residual_views import ResidualViewSet
ImportError: cannot import name 'ResidualViewSet' from 'api.views.residual_views' (/Users/davidnichamoff/Projects/FIZIT_DEV/api/views/residual_views.py)
INFO 2024-08-22 20:29:18,682 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/serializers/__init__.py changed, reloading.
INFO 2024-08-22 20:29:18,682 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/serializers/__init__.py changed, reloading.
Fetching secret value for devnet/rotating-keys from AWS Secrets Manager
Fetching secret value for devnet/static-keys from AWS Secrets Manager
Performing system checks...

Connection successful
Contract loaded
INFO 2024-08-22 20:29:19,698 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:29:19,698 autoreload Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/project/urls.py", line 9, in <module>
    path('api/', include('api.urls')), 
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/api/urls.py", line 16, in <module>
    from .views.csrf_token_views import get_csrf_token
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/api/views/__init__.py", line 14, in <module>
    from .residual_views import ResidualViewSet
ImportError: cannot import name 'ResidualViewSet' from 'api.views.residual_views' (/Users/davidnichamoff/Projects/FIZIT_DEV/api/views/residual_views.py)
INFO 2024-08-22 20:30:41,194 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/serializers/advance_serializer.py changed, reloading.
INFO 2024-08-22 20:30:41,194 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/serializers/advance_serializer.py changed, reloading.
Fetching secret value for devnet/rotating-keys from AWS Secrets Manager
Fetching secret value for devnet/static-keys from AWS Secrets Manager
Performing system checks...

Connection successful
Contract loaded
INFO 2024-08-22 20:30:42,086 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:30:42,086 autoreload Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/project/urls.py", line 9, in <module>
    path('api/', include('api.urls')), 
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/api/urls.py", line 16, in <module>
    from .views.csrf_token_views import get_csrf_token
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/api/views/__init__.py", line 14, in <module>
    from .residual_views import ResidualViewSet
ImportError: cannot import name 'ResidualViewSet' from 'api.views.residual_views' (/Users/davidnichamoff/Projects/FIZIT_DEV/api/views/residual_views.py)
INFO 2024-08-22 20:33:03,499 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/views/account_views.py changed, reloading.
INFO 2024-08-22 20:33:03,499 autoreload /Users/davidnichamoff/Projects/FIZIT_DEV/api/views/account_views.py changed, reloading.
Fetching secret value for devnet/rotating-keys from AWS Secrets Manager
Fetching secret value for devnet/static-keys from AWS Secrets Manager
Performing system checks...

Connection successful
Contract loaded
INFO 2024-08-22 20:33:05,868 autoreload Watching for file changes with StatReloader
INFO 2024-08-22 20:33:05,868 autoreload Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/project/urls.py", line 9, in <module>
    path('api/', include('api.urls')), 
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/.venv/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/api/urls.py", line 16, in <module>
    from .views.csrf_token_views import get_csrf_token
  File "/Users/davidnichamoff/Projects/FIZIT_DEV/api/views/__init__.py", line 14, in <module>
    from .residual_views import ResidualViewSet
ImportError: cannot import name 'ResidualViewSet' from 'api.views.residual_views' (/Users/davidnichamoff/Projects/FIZIT_DEV/api/views/residual_views.py)
Fetching secret value for devnet/rotating-keys from AWS Secrets Manager
Fetching secret value for devnet/static-keys from AWS Secrets Manager
